Figure for plotting Pareto frontier (Flops x Perf)
allenai/OLMo pull request #753
Opened 2024-11-27 01:53 UTC by kyleclo

2024-11-27 07:46 UTC, dirkgr requested changes
This guy plots.

2024-11-27 07:46 UTC, dirkgr commented on scripts/flops_by_perf_figure.py
> +OUTPUT_PATHS = ["/Users/kylel/ai2/olmo/olmo2.pdf", "/Users/kylel/ai2/olmo/olmo2.png"]
Hardcoded paths to your machine?

2024-12-19 05:43 UTC, soldni commented
[olmo2.pdf](https://github.com/user-attachments/files/18193095/olmo2.pdf)
made changes to achieve look above.

2024-12-19 05:44 UTC, soldni commented
made changes, now looks like: 
![olmo2](https://github.com/user-attachments/assets/7d6a51ed-d518-4cc6-a6e5-2baee7a4422c)

2025-01-07 18:38 UTC, dirkgr approved these changes

2025-01-07 18:38 UTC, merged